language: node_js
os:
  - linux
  - osx
node_js:
  - "6"
before_install:
- npm -g install npm@6
script: npm run ci
notifications:
  email: false
deploy:
  - provider: script
    script: npm run release
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ ^v?[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+"
      repo: balena-io/balena-cli
